language: c
dist: xenial
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-8
    - git-core
    - make
    - sparse
    - wget
    - libibumad-dev
    - libibmad-dev
script:
  - scripts/travis-checkpatch
  - scripts/travis-build
  - ./dist.sh
